import{S as b,N as y,P as v,A as h,a as L}from"./assets/vendor-YvgF28ec.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const e of n.addedNodes)e.tagName==="LINK"&&e.rel==="modulepreload"&&c(e)}).observe(document,{childList:!0,subtree:!0});function u(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(t){if(t.ep)return;t.ep=!0;const n=u(t);fetch(t.href,n)}})();const p=document.querySelector(".mobile-menu"),k=document.querySelector(".js-mobile-menu"),S=document.querySelector(".js-mobile-close-menu"),f=document.querySelector(".js-mobile-backdrop");function w(){p.classList.add("is-open"),f.classList.add("is-active"),document.body.classList.add("no-scroll")}function d(){p.classList.remove("is-open"),f.classList.remove("is-active"),document.body.classList.remove("no-scroll")}k.onclick=w;S.onclick=d;f.onclick=d;document.addEventListener("keydown",r=>{r.key==="Escape"&&d()});p.querySelectorAll('a[href^="#"]').forEach(r=>{r.onclick=d});const E=document.querySelector(".swiper-wrapper");document.addEventListener("DOMContentLoaded",()=>{const r=new b(".modal-product__slider",{loop:!1,modules:[y,v,h],pagination:{el:".swiper-pagination",clickable:!0,renderBullet:function(e,s){return e===0?'<span class="'+s+' bullet left" data-slide="0"></span>':e===1?'<span class="'+s+' bullet center" data-slide="middle"></span>':e===2?'<span class="'+s+' bullet right" data-slide="last"></span>':""},bulletClass:"bullet",bulletActiveClass:"swiper-pagination-bullet-active"},navigation:{nextEl:".custom-next",prevEl:".custom-prev"},autoplay:{delay:5e3},on:{init(){t(this.realIndex,this.slides.length),n(this)},slideChange(){t(this.realIndex,this.slides.length)}}});async function l(){try{const i="https://sound-wave.b.goit.study/api"+"/feedbacks",o={limit:12},a=await L.get(i,{params:o});return console.log("API Data:",a.data),a.data}catch(e){return console.error("Error fetching feedback:",e),null}}function u(e){const s=e.map(({_id:i,name:o,rating:a,descr:g})=>{const m=Math.round(a);return console.log("Rating for",o,":",m),`
          <div class="swiper-slide" data-id="${i||""}">
            <div class="rating" data-rating="${m}"></div>
            <p class='feed-back-descr'>${g||""}</p>
            <p class='feed-back-name'>${o||""}</p>
          </div>
        `}).join("");E.innerHTML=s,c(),r.update()}function c(){document.querySelectorAll(".rating").forEach(e=>{const s=parseInt(e.dataset.rating);if(isNaN(s)){console.error("Invalid rating value:",e.dataset.rating);return}e.innerHTML=`
        <span class="star-rating">
          ${[...Array(5)].map((i,o)=>`<span class="star ${o<s?"filled":""}">★</span>`).join("")}
        </span>
      `})}function t(e,s){const i=document.querySelectorAll(".swiper-pagination .bullet");i.forEach(o=>o.classList.remove("swiper-pagination-bullet-active")),e===0?i[0].classList.add("swiper-pagination-bullet-active"):e===s-1?i[2].classList.add("swiper-pagination-bullet-active"):i[1].classList.add("swiper-pagination-bullet-active")}function n(e){var s,i,o;(s=document.querySelector(".bullet.left"))==null||s.addEventListener("click",()=>{e.slideTo(0)}),(i=document.querySelector(".bullet.center"))==null||i.addEventListener("click",()=>{const a=Math.floor((total-1)/2);e.slideTo(a)}),(o=document.querySelector(".bullet.right"))==null||o.addEventListener("click",()=>{e.slideTo(e.slides.length-1)})}l().then(e=>{if(e){const s=Array.isArray(e)?e:e.results||e.data||[];u(s)}})});
//# sourceMappingURL=index.js.map
